INSERT INTO tb_pesquisa (
  calcado_favorito, cantor_favorito, esporte_favorito, filme_favorito, horas_sono,
  jogador_favorito, jogo_online_favorito, lugar_favorito, marca_preferida,
  materia_preferida, meme_favorito, viagem_dos_sonhos
) VALUES
('Tênis Nike Air Max', 'Anitta', 'Futebol', 'Vingadores: Ultimato', 7.5, 'Neymar', 'Free Fire', 'Praia de Copacabana', 'Nike', 'Matemática', 'Nazaré Confusa', 'Maldivas'),
('Chinelo Havaianas', 'Gusttavo Lima', 'Vôlei', 'Velozes e Furiosos 7', 6.0, 'Messi', 'Fortnite', 'Sítio da Vó', 'Adidas', 'História', 'Drake Hotline Bling', 'Fernando de Noronha'),
('Bota Coturno', 'Alok', 'Basquete', 'Homem-Aranha: Sem Volta Para Casa', 8.0, 'Cristiano Ronaldo', 'League of Legends', 'Campo', 'Vans', 'Educação Física', 'Já acabou Jéssica?', 'Paris'),
('Tênis All Star', 'Ludmilla', 'Futsal', 'Barbie', 7.0, 'Vini Jr', 'Valorant', 'Shopping', 'All Star', 'Artes', 'Moça do Caldo de Cana', 'Disney - Orlando'),
('Sandália Birkenstock', 'Marília Mendonça', 'Handebol', 'O Rei Leão', 8.5, 'Marta', 'Minecraft', 'Cachoeira', 'Farm', 'Português', 'Caneta Azul', 'Gramado - RS'),
('Tênis Adidas Ultraboost', 'Matuê', 'Corrida', 'Interestelar', 5.5, 'Mbappé', 'Call of Duty: Warzone', 'Academia', 'Adidas', 'Biologia', 'Stonks', 'Japão - Tóquio'),
('Crocs', 'Luan Santana', 'Natação', 'Toy Story 4', 9.0, 'Neymar', 'Roblox', 'Casa da Mãe', 'Crocs', 'Geografia', 'Cheems', 'Lençóis Maranhenses'),
('Salto Alto', 'Ivete Sangalo', 'Ginástica Artística', 'Titanic', 6.5, 'Endrick', 'GTA RP', 'Salvador - BA', 'Zara', 'Química', 'Gretchen', 'Itália - Roma'),
('Chuteira Nike Mercurial', 'Henrique e Juliano', 'Futebol', 'Tropa de Elite', 7.0, 'Ronaldinho Gaúcho', 'EA FC 24', 'Estádio Maracanã', 'Nike', 'Matemática', 'Luva de Pedreiro - Receba', 'Cataratas do Iguaçu'),
('Tênis Puma RS-X', 'Jorge e Mateus', 'Skate', 'Pantera Negra', 7.5, 'Rayssa Leal', 'Clash Royale', 'Pista de Skate', 'Puma', 'Física', 'Wojak Chorão', 'Nova York'),
('Tênis Olympikus Corre', 'Zé Neto e Cristiano', 'Atletismo', 'Divertida Mente 2', 6.0, 'Usain Bolt', 'Free Fire', 'Parque', 'Olympikus', 'Educação Física', 'Kombucha Girl', 'Bonito - MS'),
('Mocassim', 'Seu Jorge', 'Surfe', 'Cidade de Deus', 8.0, 'Gabriel Medina', 'Brawl Stars', 'Praia de Itamambuca', 'Reserva', 'Filosofia', 'This is Fine', 'Portugal - Lisboa'),
('Tênis Vans Old Skool', 'Pabllo Vittar', 'Vôlei de Praia', 'Meninas Malvadas', 7.0, 'Gabi Guimarães', 'The Sims 4', 'Balada', 'Vans', 'Sociologia', 'Woman Yelling at Cat', 'Londres'),
('Rasteirinha', 'Ana Castela', 'Rodeio', 'Moana', 7.5, 'Neymar', 'Hay Day', 'Fazenda', 'Renner', 'Matemática', 'Faz o L', 'Bariloche'),
('Bota Texana', 'Lauana Prado', 'Montaria', 'A Bela e a Fera', 6.5, 'Cristiano Ronaldo', 'Red Dead Online', 'Rancho', 'Arezzo', 'História', 'Cavalo Caramelo', 'Atacama - Chile'),
('Tênis Mizuno Wave', 'Djavan', 'Corrida de Rua', 'Forrest Gump', 5.0, 'Messi', 'Gran Turismo 7', 'Rua de Casa', 'Mizuno', 'Matemática', 'Doge', 'Egito - Pirâmides'),
('Chinelo Kenner', 'MC Ryan SP', 'Futvôlei', 'Até o Último Homem', 7.0, 'Neymar', 'PUBG Mobile', 'Praia Grande - SP', 'Kenner', 'Geografia', 'Deixa o Homem Trabalhar', 'Dubai'),
('Tênis Asics Gel', 'Emicida', 'Maratona', 'O Lobo de Wall Street', 6.0, 'Kipchoge', 'FIFA Mobile', 'Parque Ibirapuera', 'Asics', 'Português', 'Pepe the Frog', 'Grécia - Santorini'),
('Coturno Dr. Martens', 'Pitty', 'Escalada', 'Coringa', 8.0, 'Cristiano Ronaldo', 'Elden Ring', 'Show de Rock', 'Dr. Martens', 'Artes', 'Drake Sim e Não', 'Islândia - Aurora Boreal'),
('Tênis New Balance 550', 'Racionais MCs', 'Basquete', 'Space Jam', 7.5, 'LeBron James', 'NBA 2K24', 'Quadra do Bairro', 'New Balance', 'História', 'Jordan Chorando', 'Los Angeles'),
('Papete', 'Maiara e Maraisa', 'Vôlei', 'Minha Mãe é uma Peça 3', 8.5, 'Tandara', 'Candy Crush', 'Casa', 'Melissa', 'Biologia', 'Glória Pires', 'Chapada dos Veadeiros'),
('Tênis Oakley Flak', 'MC Tuto', 'Grau de Moto', 'Velozes e Furiosos 10', 6.0, 'Messi', 'Moto Wheelie 3D', 'Oficina', 'Oakley', 'Matemática', 'Bora Bill', 'Porto Seguro - BA'),
('Sapatênis Democrata', 'Chitãozinho e Xororó', 'Truco', 'Auto da Compadecida', 7.0, 'Neymar', 'Truco Online', 'Bar do Centro', 'Democrata', 'Português', 'Já acabou Jéssica', 'Foz do Iguaçu'),
('Tênis Fila Disruptor', 'Luísa Sonza', 'Dança', 'La La Land', 6.5, 'Rebeca Andrade', 'Just Dance Now', 'Estúdio de Dança', 'Fila', 'Artes', 'Piscadinha', 'Veneza - Itália'),
('Bota Caterpillar', 'Gustavo Mioto', 'Crossfit', 'Rocky Balboa', 5.5, 'Ramon Dino', 'Call of Duty Mobile', 'Box de Crossfit', 'Caterpillar', 'Educação Física', 'Gigachad', 'Toronto - Canadá'),
('Tênis Nike Shox', 'Veigh', 'Futebol', 'Carros', 7.0, 'Gabigol', 'Free Fire', 'Rua de Casa', 'Nike', 'Matemática', 'Cavalo Pepe', 'Rio de Janeiro - Cristo'),
('Chinelo Slide Nike', 'MC Hariel', 'Futebol', 'Até que a Sorte nos Separe', 8.0, 'Neymar', 'Stumble Guys', 'Baile Funk', 'Nike', 'História', 'Vem tranquilo?', 'Recife - Olinda'),
('Tênis Converse Run Star', 'Iza', 'Yoga', 'Comer Rezar Amar', 7.5, 'Marta', 'Genshin Impact', 'Estúdio de Yoga', 'Converse', 'Filosofia', 'Surprised Pikachu', 'Bali - Indonésia'),
('Sapatilha Moleca', 'Simone Mendes', 'Pilates', 'Diário de uma Paixão', 9.0, 'Marta', 'Homescapes', 'Casa', 'Moleca', 'Português', 'Nazaré Tedesco', 'Campos do Jordão'),
('Tênis Tesla Coil', 'Charlie Brown Jr', 'Skate', 'Vida de Inseto - Skate', 6.0, 'Sandro Dias', 'Skate City', 'Pista', 'Tesla', 'Sociologia', 'Chad Sim', 'Califórnia'),
('Bota de Borracha', 'Boiadeira', 'Laço', 'Faroeste Caboclo', 5.0, 'Cristiano Ronaldo', 'Farming Simulator', 'Fazenda São João', 'Havaianas', 'Matemática', 'Boiadeira', 'Pantanal'),
('Tênis Redley', 'Orochi', 'Basquete', 'Karatê Kid', 7.0, 'Stephen Curry', 'NBA Live Mobile', 'Shopping', 'Redley', 'Geografia', 'Oruam', 'Medellín - Colômbia'),
('Salto Anabela', 'Alcione', 'Samba', 'Cheias de Charme', 8.0, 'Formiga', 'Ludo King', 'Sambódromo', 'Schutz', 'História', 'Inês Brasil', 'Salvador'),
('Chuteira Adidas Predator', 'Ferrugem', 'Futsal', 'Gol - O Sonho Impossível', 6.5, 'Falcão Futsal', 'Dream League Soccer', 'Ginásio', 'Adidas', 'Educação Física', 'Manoel Gomes', 'Barcelona - Espanha'),
('Tênis Hoka', 'Caetano Veloso', 'Trilha', 'Na Natureza Selvagem', 7.0, 'Messi', 'Pokémon GO', 'Morro do Cristo - São João', 'Hoka', 'Biologia', 'Grumpy Cat', 'Machu Picchu - Peru'),
('Sapatênis Ferracini', 'Leonardo', 'Sinuca', 'A Lenda do Campeão', 6.0, 'Baianinho de Mauá', '8 Ball Pool', 'Bar', 'Ferracini', 'Matemática', 'Faustão - Errou', 'Las Vegas'),
('Tênis Nike Air Force', 'Rihanna', 'Hip Hop Dance', '8 Mile', 7.5, 'LeBron James', 'Fortnite', 'Batalha de Rima', 'Nike', 'Inglês', 'Distracted Boyfriend', 'Miami'),
('Bota Over the Knee', 'Beyoncé', 'Pole Dance', 'Flashdance', 8.0, 'Marta', 'Avakin Life', 'Balada Top', 'Luiza Barcelos', 'Artes', 'Beyoncé Visual', 'Paris - Torre Eiffel'),
('Tênis Mormaii', 'Lulu Santos', 'Surfe', 'Soul Surfer', 7.0, 'Ítalo Ferreira', 'Surf GO', 'Praia de Maresias', 'Mormaii', 'Geografia', 'John Travolta Confuso', 'Havaí'),
('Chinelo Rider', 'Xand Avião', 'Forró', 'Cine Holliúdy', 6.5, 'Hulk', 'Forró no Sítio', 'São João de Campina Grande', 'Rider', 'Português', 'Meme do São João', 'Caribe'),
('Tênis Puma Suede', 'Gilberto Gil', 'Capoeira', 'Besouro', 8.0, 'Neymar', 'Capoeira Legends', 'Roda de Capoeira', 'Puma', 'História', 'Nazaré Capoeira', 'Angola'),
('Tênis Qix Chorão', 'Raimundos', 'Skate Street', 'Os Parças', 5.5, 'Luan Oliveira', 'True Skate', 'Centro', 'Qix', 'Sociologia', 'Vesgo e Silvio', 'Amsterdã'),
('Tênis Kappa', 'MC Livinho', 'Futebol de Várzea', 'O Malandro', 7.0, 'Adriano Imperador', 'eFootball 2024', 'Campinho', 'Kappa', 'Matemática', 'Tite - Fala Muito', 'Buenos Aires'),
('Bota UGG', 'Taylor Swift', 'Patinação no Gelo', 'Frozen', 8.5, 'Marta', 'Subway Surfers', 'Shopping', 'UGG', 'Inglês', 'Taylor Surprised', 'Alpes Suíços'),
('Tênis Lacoste', 'Thiaguinho', 'Pagode', 'Pagode da Ofensa', 6.0, 'Neymar', 'Dominó Online', 'Pagode na Laje', 'Lacoste', 'Português', 'É sobre isso', 'Curitiba - Jardim Botânico'),
('Chinelo Ipanema', 'Marina Sena', 'Vôlei de Areia', 'Mamma Mia', 7.5, 'Gabi Guimarães', 'Beach Buggy Racing', 'Praia de Ipanema', 'Ipanema', 'Geografia', 'Sonic Ugh', 'Fernando de Noronha'),
('Tênis Nike Dunk Low', 'Travis Scott', 'Basquete', 'Aranhaverso', 6.0, 'Michael Jordan', 'Fortnite', 'Rua Augusta - SP', 'Nike', 'Artes', 'Wojak de Máscara', 'Tóquio - Shibuya'),
('Coturno Militar', 'Legião Urbana', 'Airsoft', 'Resgate do Soldado Ryan', 5.0, 'Cristiano Ronaldo', 'Warzone Mobile', 'Campo de Airsoft', 'Aventura', 'História', 'Meme do Soldado', 'Berlim'),
('Tênis Adidas Yeezy', 'Kanye West', 'Streetball', 'Space Jam 2', 7.0, 'Ja Morant', 'NBA 2K Mobile', 'Quadra Aberta', 'Adidas', 'Inglês', 'Kanye Interrupting', 'Dubai - Burj Khalifa'),
('Havaianas Tradicional', 'Alceu Valença', 'Forró Pé de Serra', 'Auto da Compadecida 2', 8.0, 'Neymar', 'Free Fire', 'Festa Junina de São João - PR', 'Havaianas', 'Português', 'Bode Gaiato', 'Jericoacoara - CE');